# Generated by Django 2.1.2 on 2018-11-29 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('barcode', models.UUIDField(default=uuid.uuid4, verbose_name='BarCode')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('stock_available', models.IntegerField(default=0, verbose_name='Stock available')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('max_allowed_items', models.IntegerField(verbose_name='Max allowed items')),
                ('description', models.TextField(verbose_name='Description')),
                ('temperature', models.IntegerField(default=25, verbose_name='Temperature')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='storage.Section'),
        ),
    ]
